---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca
  labels:
    run: blockchain-ca
spec:
  type: NodePort
  selector:
    name: ca
  ports:
  - protocol: TCP
    nodePort: 30054
    targetPort: 7054
    port: 30054
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    nodePort: 31010
    targetPort: 31010
    port: 31010
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org1peer1
  labels:
    run: blockchain-org1peer1
spec:
  type: NodePort
  selector:
    name: org1peer1
  ports:
  - protocol: TCP
    nodePort: 30110
    targetPort: 30110
    port: 30110
    name: grpc
  - protocol: TCP
    nodePort: 30111
    targetPort: 30111
    port: 30111
    name: events
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org2peer1
  labels:
    run: blockchain-org2peer1
spec:
  type: NodePort
  selector:
    name: org2peer1
  ports:
  - protocol: TCP
    nodePort: 30210
    targetPort: 30210
    port: 30210
    name: grpc
  - protocol: TCP
    nodePort: 30211
    targetPort: 30211
    port: 30211
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org3peer1
  labels:
    run: blockchain-org3peer1
spec:
  type: NodePort
  selector:
    name: org3peer1
  ports:
  - protocol: TCP
    nodePort: 30310
    targetPort: 30310
    port: 30310
    name: grpc
  - protocol: TCP
    nodePort: 30311
    targetPort: 30311
    port: 30311
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org4peer1
  labels:
    run: blockchain-org4peer1
spec:
  type: NodePort
  selector:
    name: org4peer1
  ports:
  - protocol: TCP
    nodePort: 30410
    targetPort: 30410
    port: 30410
    name: grpc
  - protocol: TCP
    nodePort: 30411
    targetPort: 30411
    port: 30411
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org5peer1
  labels:
    run: blockchain-org5peer1
spec:
  type: NodePort
  selector:
    name: org5peer1
  ports:
  - protocol: TCP
    nodePort: 30510
    targetPort: 30510
    port: 30510
    name: grpc
  - protocol: TCP
    nodePort: 30511
    targetPort: 30511
    port: 30511
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org5peer2
  labels:
    run: blockchain-org5peer2
spec:
  type: NodePort
  selector:
    name: org5peer2
  ports:
  - protocol: TCP
    nodePort: 30501
    targetPort: 30501
    port: 30501
    name: grpc
  - protocol: TCP
    nodePort: 30502
    targetPort: 30502
    port: 30502
    name: events
